import os
import time
from datetime import datetime

import anthropic

from config import ANTHROPIC_API_KEY, CLAUDE_MODEL, TRANSCRIPTS_DIR
from utils import logger

CHUNK_SIZE = 160000
CHUNK_OVERLAP = 2000

CLEAN_SYSTEM_PROMPT = """You are a transcript correction specialist. The transcript was generated by Whisper (an AI speech-to-text model) and may contain errors — especially with proper nouns, technical terms, brand names, and domain-specific jargon.

Your job:
- Fix speech-to-text misrecognitions (e.g. "clawd" → "Claude", "anthropic" → "Anthropic", "pie thon" → "Python")
- Correct homophones and phonetic guesses that are wrong in context (e.g. "their" vs "there", "two" vs "too")
- Fix run-on words or incorrectly split words
- Preserve the original meaning, structure, and speaker's voice exactly
- Do NOT summarize, rewrite, or add content
- Do NOT change correct words
- Return ONLY the corrected transcript text, nothing else"""

TASK_MENU = [
    ("Summarize the video", "Please provide a comprehensive summary of the following transcript."),
    ("Extract key points as bullet list", "Extract the most important key points from this transcript as a clean bullet list."),
    ("Generate detailed notes", "Generate detailed, well-structured notes from this transcript suitable for study or reference."),
    ("Extract all action items / to-dos", "Extract every action item, task, or to-do mentioned in this transcript. Format as a numbered list."),
    ("Translate transcript to another language", "Translate the following transcript. Please ask which language if not specified, or default to Spanish."),
    ("Answer a specific question about the video", "Answer questions about the following transcript content."),
    ("Generate a blog post from the content", "Write a well-structured, engaging blog post based on the content of this transcript."),
    ("Custom instruction", None),
]


def _build_prompt(transcript: str, task_instruction: str) -> str:
    return (
        f"{task_instruction}\n\n"
        f"---\nTRANSCRIPT:\n{transcript}\n---"
    )


def _stream_response(client: anthropic.Anthropic, prompt: str) -> str:
    output = []
    print()
    with client.messages.stream(
        model=CLAUDE_MODEL,
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        for text in stream.text_stream:
            print(text, end="", flush=True)
            output.append(text)
    print("\n")
    return "".join(output)


def _process_chunks(client: anthropic.Anthropic, transcript: str, task_instruction: str) -> str:
    chunks = []
    start = 0
    while start < len(transcript):
        end = start + CHUNK_SIZE
        chunks.append(transcript[start:end])
        start = end - CHUNK_OVERLAP

    logger.info(f"Transcript chunked into {len(chunks)} parts for processing...")
    results = []

    for i, chunk in enumerate(chunks, 1):
        logger.info(f"Processing chunk {i}/{len(chunks)}...")
        chunk_prompt = (
            f"{task_instruction}\n\n"
            f"Note: This is part {i} of {len(chunks)} of the full transcript.\n\n"
            f"---\nTRANSCRIPT PART {i}:\n{chunk}\n---"
        )
        for attempt in range(3):
            try:
                result = _stream_response(client, chunk_prompt)
                results.append(result)
                break
            except anthropic.RateLimitError:
                wait = 30 * (attempt + 1)
                logger.warning(f"Rate limit hit — waiting {wait}s before retry...")
                time.sleep(wait)

    if len(results) > 1:
        merge_prompt = (
            "You processed a long transcript in multiple parts. "
            "Below are the outputs from each part. "
            "Please merge them into one coherent, unified response:\n\n"
            + "\n\n---\n\n".join(f"PART {i+1}:\n{r}" for i, r in enumerate(results))
        )
        logger.info("Merging chunk outputs...")
        merged = _stream_response(client, merge_prompt)
        return merged

    return results[0] if results else ""


def clean_transcript(transcript: str, client: anthropic.Anthropic) -> str:
    logger.step("✏", "Cleaning transcript (fixing speech-to-text errors)...")

    # Process in chunks if transcript is very long
    if len(transcript) <= CHUNK_SIZE:
        chunks = [transcript]
    else:
        chunks = []
        start = 0
        while start < len(transcript):
            chunks.append(transcript[start:start + CHUNK_SIZE])
            start += CHUNK_SIZE - CHUNK_OVERLAP

    cleaned_parts = []
    for i, chunk in enumerate(chunks, 1):
        if len(chunks) > 1:
            logger.info(f"Cleaning chunk {i}/{len(chunks)}...")
        for attempt in range(3):
            try:
                output = []
                with client.messages.stream(
                    model=CLAUDE_MODEL,
                    max_tokens=16000,
                    system=CLEAN_SYSTEM_PROMPT,
                    messages=[{"role": "user", "content": chunk}],
                ) as stream:
                    for text in stream.text_stream:
                        output.append(text)
                cleaned_parts.append("".join(output))
                break
            except anthropic.RateLimitError:
                wait = 30 * (attempt + 1)
                logger.warning(f"Rate limit — waiting {wait}s...")
                time.sleep(wait)

    cleaned = " ".join(cleaned_parts)
    logger.success("Transcript cleaned")
    return cleaned


def process_transcript(transcript: str, task: str, base_name: str) -> str:
    if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_anthropic_api_key_here":
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set.\n"
            "  Add your API key to the .env file.\n"
            "  Get one at: https://console.anthropic.com/"
        )

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    try:
        transcript = clean_transcript(transcript, client)
        # Overwrite the raw transcript file with the cleaned version
        txt_path = os.path.join(TRANSCRIPTS_DIR, f"{base_name}.txt")
        if os.path.exists(txt_path):
            with open(txt_path, "w", encoding="utf-8") as f:
                f.write(transcript)
    except Exception as e:
        logger.warning(f"Transcript cleaning skipped: {e}")

    logger.step("🤖", f"Claude is processing ({CLAUDE_MODEL})...")

    try:
        if len(transcript) > CHUNK_SIZE:
            logger.info(f"Long transcript ({len(transcript):,} chars) — chunking enabled")
            output = _process_chunks(client, transcript, task)
        else:
            prompt = _build_prompt(transcript, task)
            output = _stream_response(client, prompt)

    except anthropic.AuthenticationError:
        raise RuntimeError(
            "Invalid Anthropic API key.\n"
            "  Check your ANTHROPIC_API_KEY in the .env file."
        )
    except anthropic.RateLimitError:
        raise RuntimeError("Anthropic rate limit reached. Please wait and try again.")
    except anthropic.BadRequestError as e:
        raise RuntimeError(f"Claude rejected the request: {e}")

    out_path = os.path.join(TRANSCRIPTS_DIR, f"{base_name}_processed.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)
    logger.success(f"Output saved: {out_path}")

    return output
